name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  # 👈 Usa el entorno que creaste en GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t stripe-app .

      - name: Run Docker container
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
        run: |
          docker run -d --name stripe-container \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
            -p 8080:8080 stripe-app

      - name: Wait for app to start
        run: |
          echo "Esperando que la app arranque..."
          sleep 15

      - name: Health check
        run: |
          curl --fail http://localhost:8080/actuator/health
