name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t stripe-app .

      - name: Run Docker container
        run: |
          docker run -d --name stripe-container \
            -p 8080:8080 stripe-app

      - name: Wait for app to start
        run: |
          echo "Esperando que la app arranque..."
          sleep 15

      - name: Health check
        run: |
          curl --fail http://localhost:8080/actuator/health
